{
 "title": "GPU Assessment",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gpu_type",
    "label": "GPU Type",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_FREE,modelName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_FB_FREE{modelName=~\"$gpu_type\"})",
     "legendFormat": "Total GPUs"
    },
    {
     "expr": "count(group(group(kube_pod_info) by(pod, namespace, node) * on(node) group_left(modelName) (group(DCGM_FI_DEV_FB_FREE{node!=\"\", modelName=~\"$gpu_type\"}) by(node, modelName) or group(label_replace(DCGM_FI_DEV_FB_FREE{modelName=~\"$gpu_type\"}, \"pod_ip\", \"$1\", \"instance\", \"(.*):(.*)\") * on (pod_ip) group_left(node) kube_pod_info{created_by_name=~\".*dcgm-exporter\", pod_ip!=\"\"}) by(node, modelName)) * on(pod, namespace) group_left() group(kube_pod_status_phase{phase=\"Running\"}==1) by(pod, namespace) * on(pod, namespace) group_left() sum(max(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by(container, pod, namespace)) by(pod, namespace)) by(pod, namespace) * on(pod, namespace) group_right() (label_replace(label_replace(DCGM_FI_DEV_GPU_UTIL{modelName=~\"$gpu_type\", exported_pod!=\"\", exported_namespace!=\"\"}>0, \"pod\", \"$1\", \"exported_pod\", \"(.*)\"), \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\") or DCGM_FI_DEV_GPU_UTIL{modelName=~\"$gpu_type\"}>0)) or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "Used Allocated GPUs"
    },
    {
     "expr": "count(group(group(kube_pod_info) by(pod, namespace, node) * on(node) group_left(modelName) (group(DCGM_FI_DEV_FB_FREE{node!=\"\", modelName=~\"$gpu_type\"}) by(node, modelName) or group(label_replace(DCGM_FI_DEV_FB_FREE{modelName=~\"$gpu_type\"}, \"pod_ip\", \"$1\", \"instance\", \"(.*):(.*)\") * on (pod_ip) group_left(node) kube_pod_info{created_by_name=~\".*dcgm-exporter\", pod_ip!=\"\"}) by(node, modelName)) * on(pod, namespace) group_left() group(kube_pod_status_phase{phase=\"Running\"}==1) by(pod, namespace) * on(pod, namespace) group_left() sum(max(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by(container, pod, namespace)) by(pod, namespace)) by(pod, namespace) * on(pod, namespace) group_right() (label_replace(label_replace(DCGM_FI_DEV_GPU_UTIL{modelName=~\"$gpu_type\", exported_pod!=\"\", exported_namespace!=\"\"}==0, \"pod\", \"$1\", \"exported_pod\", \"(.*)\"), \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\") or DCGM_FI_DEV_GPU_UTIL{modelName=~\"$gpu_type\"}==0)) or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "Idle Allocated GPUs"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info) by(pod, namespace, node) * on(node) group_left(modelName) (group(DCGM_FI_DEV_FB_FREE{node!=\"\", modelName=~\"$gpu_type\"}) by(node, modelName) or group(label_replace(DCGM_FI_DEV_FB_FREE{modelName=~\"$gpu_type\"}, \"pod_ip\", \"$1\", \"instance\", \"(.*):(.*)\") * on (pod_ip) group_left(node) kube_pod_info{created_by_name=~\".*dcgm-exporter\", pod_ip!=\"\"}) by(node, modelName)) * on(pod, namespace) group_left() group(kube_pod_status_phase{phase=\"Running\"}==1) by(pod, namespace) * on(pod, namespace) group_left() sum(max(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by(container, pod, namespace)) by(pod, namespace)) / count(DCGM_FI_DEV_FB_FREE{modelName=~\"$gpu_type\"}) * 100 or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{modelName=~\"$gpu_type\"}) or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{modelName=~\"$gpu_type\"}) or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_FREE{modelName=~\"$gpu_type\"}) + sum(DCGM_FI_DEV_FB_USED{modelName=~\"$gpu_type\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{modelName=~\"$gpu_type\"}) or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{modelName=~\"$gpu_type\"}) / (sum(DCGM_FI_DEV_FB_FREE{modelName=~\"$gpu_type\"}) + sum(DCGM_FI_DEV_FB_USED{modelName=~\"$gpu_type\"})) * 100 or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Running GPU Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "GPU Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "panels": [
    {
     "title": "GPU Temperature (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_GPU_TEMP{modelName=~\"$gpu_type\"}) by (modelName)",
       "legendFormat": "{{modelName}}"
      }
     ]
    },
    {
     "title": "GPU Max Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "max(DCGM_FI_DEV_GPU_TEMP{modelName=~\"$gpu_type\"}) by (modelName)",
       "legendFormat": "{{modelName}}"
      }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(group(kube_pod_info) by(pod, namespace, node) * on(node) group_left(modelName) (group(DCGM_FI_DEV_FB_FREE{node!=\"\", modelName=~\"$gpu_type\"}) by(node, modelName) or group(label_replace(DCGM_FI_DEV_FB_FREE{modelName=~\"$gpu_type\"}, \"pod_ip\", \"$1\", \"instance\", \"(.*):(.*)\") * on (pod_ip) group_left(node) kube_pod_info{created_by_name=~\".*dcgm-exporter\", pod_ip!=\"\"}) by(node, modelName)) * on(pod, namespace) group_left() group(kube_pod_status_phase{phase=\"Running\"}==1) by(pod, namespace) * on(pod, namespace) group_left() group(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by(pod, namespace)) or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(kube_pod_info) by(pod, namespace, node) * on(node) group_left(modelName) (group(DCGM_FI_DEV_FB_FREE{node!=\"\", modelName=~\"$gpu_type\"}) by(node, modelName) or group(label_replace(DCGM_FI_DEV_FB_FREE{modelName=~\"$gpu_type\"}, \"pod_ip\", \"$1\", \"instance\", \"(.*):(.*)\") * on (pod_ip) group_left(node) kube_pod_info{created_by_name=~\".*dcgm-exporter\", pod_ip!=\"\"}) by(node, modelName)) * on(pod, namespace) group_left() group(kube_pod_status_phase{phase=\"Running\"}==1) by(pod, namespace) * on(pod, namespace) group_left() group(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by(pod, namespace)) or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Inefficient Pods",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bottomk(10, avg(group(group(kube_pod_info) by(pod, namespace, node) * on(node) group_left(modelName) (group(DCGM_FI_DEV_FB_FREE{node!=\"\", modelName=~\"$gpu_type\"}) by(node, modelName) or group(label_replace(DCGM_FI_DEV_FB_FREE{modelName=~\"$gpu_type\"}, \"pod_ip\", \"$1\", \"instance\", \"(.*):(.*)\") * on (pod_ip) group_left(node) kube_pod_info{created_by_name=~\".*dcgm-exporter\", pod_ip!=\"\"}) by(node, modelName)) * on(pod, namespace) group_left() group(kube_pod_status_phase{phase=\"Running\"}==1) by(pod, namespace) * on(pod, namespace) group_left() sum(max(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by(container, pod, namespace)) by(pod, namespace)) by(pod, namespace, node) * on(pod, namespace) group_right(node) (label_replace(label_replace(DCGM_FI_DEV_GPU_UTIL{modelName=~\"$gpu_type\", exported_pod!=\"\", exported_namespace!=\"\"}, \"pod\", \"$1\", \"exported_pod\", \"(.*)\"), \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\") or DCGM_FI_DEV_GPU_UTIL{modelName=~\"$gpu_type\"})) by(pod, namespace, node))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pending GPU Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(group(kube_pod_status_phase{phase=\"Pending\"}==1) by(pod, namespace) * on(pod, namespace) group(max(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by(pod, namespace, container)) by(pod, namespace)) or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(kube_pod_status_phase{phase=\"Pending\"}==1) by(pod, namespace) * on(pod, namespace) group(max(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by(pod, namespace, container)) by(pod, namespace)) or count(DCGM_FI_DEV_FB_FREE)*0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}